### ISSUE TITLE
Get/SetProperty(DIPH_DEVICE, ...) unimplemented

### ISSUE THREAD

**Issue by DLZ-AU** [jmgao/dhc#15]
[dhc.log](https://github.com/jmgao/dhc/files/3474705/dhc.log)

Trying to run BBCF (Blazblue Centralfiction) using my Qanba Obsidian and I get this message, it also shuts down automatically when I have my stick unplugged and start it up

Please, for the love of god, continue this godlike project and free us from the shackles of arse PC ports!

**Comment by jmgao** [comment]
It's probably not related to the stick. Can you edit the config file (dhc.toml in the game directory) and set  log_level to "trace", launch the game again, and upload that?

**Comment by DLZ-AU** [comment]
[dhc.log](https://github.com/jmgao/dhc/files/3474724/dhc.log)
Here ya go boss

**Comment by jmgao** [comment]
Oops, yeah, I forgot to implement something. I'll take a look at fixing it tonight.

**Comment by jmgao** [comment]
Give [this version](https://github.com/jmgao/dhc/files/3475169/dhc-bbcf.zip) a try, it seems to work for me. I'll cut a real release once I implement some UNI-specific features that I've been meaning to do for a while.

**Comment by DLZ-AU** [comment]
Absolutely incredible, thanks!
